from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Any

import pandas as pd
import pandas_ta as ta
from loguru import logger


class Direction(str, Enum):
    """Trade direction."""
    BUY = "BUY"
    SELL = "SELL"


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    direction: Direction
    entry_price: float
    sl: float
    tp: float
    strategy_name: str
    timestamp: datetime
    trailing_stop_trigger: float | None = None
    trailing_stop_distance: float | None = None
    # Learning system fields
    confidence: float = 0.0
    features: dict[str, Any] | None = None
    regime: str = ""
    reasoning: str = ""


class Strategy(ABC):
    """Abstract base class for trading strategies."""

    @property
    @abstractmethod
    def name(self) -> str:
        """Strategy name identifier."""
        ...

    @abstractmethod
    def analyze(self, df: pd.DataFrame) -> Signal | None:
        """Analyze price data and generate a trading signal.

        Args:
            df: OHLCV DataFrame with columns: datetime, open, high, low, close, volume.

        Returns:
            Signal if conditions are met, None otherwise.
        """
        ...


class EMACrossoverStrategy(Strategy):
    """EMA(9)/EMA(21) crossover strategy with RSI filter."""

    def __init__(
        self,
        fast_ema: int = 9,
        slow_ema: int = 21,
        rsi_period: int = 14,
        rsi_overbought: float = 70.0,
        rsi_oversold: float = 30.0,
        atr_period: int = 14,
        sl_atr_multiplier: float = 1.5,
        tp_sl_ratio: float = 2.0,
        trailing_atr_trigger: float = 1.0,
    ) -> None:
        self._fast_ema = fast_ema
        self._slow_ema = slow_ema
        self._rsi_period = rsi_period
        self._rsi_overbought = rsi_overbought
        self._rsi_oversold = rsi_oversold
        self._atr_period = atr_period
        self._sl_atr_multiplier = sl_atr_multiplier
        self._tp_sl_ratio = tp_sl_ratio
        self._trailing_atr_trigger = trailing_atr_trigger

    @property
    def name(self) -> str:
        return "ema_crossover"

    def analyze(self, df: pd.DataFrame) -> Signal | None:
        """Analyze for EMA crossover signals with RSI filter."""
        if len(df) < self._slow_ema + 2:
            logger.debug("Not enough data for EMA crossover analysis")
            return None

        # Calculate indicators
        df = df.copy()
        df[f"ema_{self._fast_ema}"] = ta.ema(df["close"], length=self._fast_ema)
        df[f"ema_{self._slow_ema}"] = ta.ema(df["close"], length=self._slow_ema)
        df["rsi"] = ta.rsi(df["close"], length=self._rsi_period)
        df["atr"] = ta.atr(df["high"], df["low"], df["close"], length=self._atr_period)

        fast_col = f"ema_{self._fast_ema}"
        slow_col = f"ema_{self._slow_ema}"
        curr = df.iloc[-1]

        # Check for NaN values
        if any(pd.isna([curr[fast_col], curr[slow_col], curr["rsi"], curr["atr"]])):
            return None

        atr = curr["atr"]
        sl_distance = atr * self._sl_atr_multiplier
        tp_distance = sl_distance * self._tp_sl_ratio
        trailing_trigger = atr * self._trailing_atr_trigger
        trailing_distance = atr * self._sl_atr_multiplier

        # Scan last 5 bars for a recent crossover (more robust than just last 2)
        lookback = min(5, len(df) - 1)
        for i in range(len(df) - lookback, len(df)):
            prev = df.iloc[i - 1]
            bar = df.iloc[i]

            # Bullish crossover: fast crosses above slow
            if prev[fast_col] <= prev[slow_col] and bar[fast_col] > bar[slow_col]:
                if curr["rsi"] < self._rsi_overbought:
                    entry = curr["close"]
                    return Signal(
                        direction=Direction.BUY,
                        entry_price=entry,
                        sl=entry - sl_distance,
                        tp=entry + tp_distance,
                        strategy_name=self.name,
                        timestamp=curr.get("datetime", datetime.now()),
                        trailing_stop_trigger=trailing_trigger,
                        trailing_stop_distance=trailing_distance,
                    )
                logger.debug(f"Bullish crossover filtered by RSI: {curr['rsi']:.1f}")

            # Bearish crossover: fast crosses below slow
            if prev[fast_col] >= prev[slow_col] and bar[fast_col] < bar[slow_col]:
                if curr["rsi"] > self._rsi_oversold:
                    entry = curr["close"]
                    return Signal(
                        direction=Direction.SELL,
                        entry_price=entry,
                        sl=entry + sl_distance,
                        tp=entry - tp_distance,
                        strategy_name=self.name,
                        timestamp=curr.get("datetime", datetime.now()),
                        trailing_stop_trigger=trailing_trigger,
                        trailing_stop_distance=trailing_distance,
                    )
                logger.debug(f"Bearish crossover filtered by RSI: {curr['rsi']:.1f}")

        return None


class AsianRangeBreakoutStrategy(Strategy):
    """Asian session range breakout strategy.

    Detects the high/low of the Asian session (00:00-08:00 UTC) and generates
    breakout signals during London/NY sessions (08:00-20:00 UTC) when price
    breaks above the range high or below the range low, with an ATR buffer.
    """

    def __init__(
        self,
        asian_start_hour: int = 0,
        asian_end_hour: int = 8,
        active_start_hour: int = 8,
        active_end_hour: int = 20,
        atr_period: int = 14,
        atr_buffer_multiplier: float = 0.2,
        min_range_pips: float = 3.0,
        max_range_pips: float = 30.0,
        tp_sl_ratio: float = 2.0,
    ) -> None:
        self._asian_start_hour = asian_start_hour
        self._asian_end_hour = asian_end_hour
        self._active_start_hour = active_start_hour
        self._active_end_hour = active_end_hour
        self._atr_period = atr_period
        self._atr_buffer_multiplier = atr_buffer_multiplier
        self._min_range_pips = min_range_pips
        self._max_range_pips = max_range_pips
        self._tp_sl_ratio = tp_sl_ratio

    @property
    def name(self) -> str:
        return "asian_breakout"

    def analyze(self, df: pd.DataFrame) -> Signal | None:
        if len(df) < self._atr_period + 2:
            logger.debug("Not enough data for Asian breakout analysis")
            return None

        df = df.copy()
        df["atr"] = ta.atr(df["high"], df["low"], df["close"], length=self._atr_period)

        curr = df.iloc[-1]
        curr_dt: datetime = curr["datetime"]

        # Check if current candle is within active hours
        if not (self._active_start_hour <= curr_dt.hour < self._active_end_hour):
            logger.debug(f"Outside active hours: {curr_dt.hour}")
            return None

        # Extract Asian session candles for the current day
        asian_mask = df["datetime"].apply(
            lambda dt: dt.date() == curr_dt.date()
            and self._asian_start_hour <= dt.hour < self._asian_end_hour
        )
        asian_candles = df.loc[asian_mask]

        if asian_candles.empty:
            logger.debug("No Asian session candles found")
            return None

        range_high: float = asian_candles["high"].max()
        range_low: float = asian_candles["low"].min()
        range_width = range_high - range_low

        # Range-width filter (XAU/USD pips = dollars)
        if range_width < self._min_range_pips or range_width > self._max_range_pips:
            logger.debug(
                f"Range width {range_width:.2f} outside limits "
                f"[{self._min_range_pips}, {self._max_range_pips}]"
            )
            return None

        atr = curr["atr"]
        if pd.isna(atr):
            return None

        buffer = atr * self._atr_buffer_multiplier
        upper_level = range_high + buffer
        lower_level = range_low - buffer
        close: float = curr["close"]

        if close > upper_level:
            # Bullish breakout
            sl = range_low
            sl_distance = close - sl
            tp = close + sl_distance * self._tp_sl_ratio
            return Signal(
                direction=Direction.BUY,
                entry_price=close,
                sl=sl,
                tp=tp,
                strategy_name=self.name,
                timestamp=curr_dt,
            )

        if close < lower_level:
            # Bearish breakout
            sl = range_high
            sl_distance = sl - close
            tp = close - sl_distance * self._tp_sl_ratio
            return Signal(
                direction=Direction.SELL,
                entry_price=close,
                sl=sl,
                tp=tp,
                strategy_name=self.name,
                timestamp=curr_dt,
            )

        return None
